services:
  postgres:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: tech_market
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tech_market"]
      interval: 2s
      timeout: 3s
      retries: 20
